/* Generated By:JavaCC: Do not edit this line. cminusparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface cminusparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONDICIONAL_IF = 1;
  /** RegularExpression Id. */
  int CONDICIONAL_ELSE = 2;
  /** RegularExpression Id. */
  int DATO_INT = 3;
  /** RegularExpression Id. */
  int DATO_FLOAT = 4;
  /** RegularExpression Id. */
  int DATO_CHAR = 5;
  /** RegularExpression Id. */
  int RETORNAR_RETURN = 6;
  /** RegularExpression Id. */
  int VACIO_VOID = 7;
  /** RegularExpression Id. */
  int CICLO_WHILE = 8;
  /** RegularExpression Id. */
  int SIMBOLO_MAS = 9;
  /** RegularExpression Id. */
  int SIMBOLO_MENOS = 10;
  /** RegularExpression Id. */
  int SIMBOLO_POR = 11;
  /** RegularExpression Id. */
  int SIMBOLO_DIVISION = 12;
  /** RegularExpression Id. */
  int SIMBOLO_MODULO = 13;
  /** RegularExpression Id. */
  int SIMBOLO_MENOR_QUE = 14;
  /** RegularExpression Id. */
  int SIMBOLO_MENOR_IGUAL = 15;
  /** RegularExpression Id. */
  int SIMBOLO_MAYOR_QUE = 16;
  /** RegularExpression Id. */
  int SIMBOLO_MAYOR_IGUAL = 17;
  /** RegularExpression Id. */
  int SIMBOLO_COMPARACION = 18;
  /** RegularExpression Id. */
  int SIMBOLO_DIFERENTE = 19;
  /** RegularExpression Id. */
  int SIMBOLO_ASIGNACION = 20;
  /** RegularExpression Id. */
  int SIMBOLO_PUNTO_Y_COMA = 21;
  /** RegularExpression Id. */
  int SIMBOLO_COMA = 22;
  /** RegularExpression Id. */
  int SIMBOLO_PUNTO = 23;
  /** RegularExpression Id. */
  int SIMBOLO_COMILLA_SIMPLE = 24;
  /** RegularExpression Id. */
  int SIMBOLO_COMILLA_DOBLE = 25;
  /** RegularExpression Id. */
  int SIMBOLO_PARENTESIS_ABIERTO = 26;
  /** RegularExpression Id. */
  int SIMBOLO_PARENTESIS_CERRADO = 27;
  /** RegularExpression Id. */
  int SIMBOLO_CORCHETE_ABIERTO = 28;
  /** RegularExpression Id. */
  int SIMBOLO_CORCHETE_CERRADO = 29;
  /** RegularExpression Id. */
  int SIMBOLO_LLAVE_ABIERTA = 30;
  /** RegularExpression Id. */
  int SIMBOLO_LLAVE_CERRADA = 31;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 32;
  /** RegularExpression Id. */
  int NUMERO_REAL = 33;
  /** RegularExpression Id. */
  int CARACTER = 34;
  /** RegularExpression Id. */
  int SIMBOLO_GUION_BAJO = 35;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 36;
  /** RegularExpression Id. */
  int LETRA = 37;
  /** RegularExpression Id. */
  int DIGITO = 38;
  /** RegularExpression Id. */
  int ESPACIO = 39;
  /** RegularExpression Id. */
  int NUEVA_LINEA = 40;
  /** RegularExpression Id. */
  int RETORNO_DE_CARRO = 41;
  /** RegularExpression Id. */
  int TABULACION = 42;
  /** RegularExpression Id. */
  int COMENTARIO_LINEAL = 43;
  /** RegularExpression Id. */
  int ERROR_CARACTER = 47;
  /** RegularExpression Id. */
  int ERROR_NUMERO_REAL = 48;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR = 49;
  /** RegularExpression Id. */
  int ERROR_SIMBOLO_INVALIDO = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int DENTRO_COMENTARIO = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "<SIMBOLO_MAS>",
    "<SIMBOLO_MENOS>",
    "<SIMBOLO_POR>",
    "<SIMBOLO_DIVISION>",
    "<SIMBOLO_MODULO>",
    "<SIMBOLO_MENOR_QUE>",
    "\"<=\"",
    "<SIMBOLO_MAYOR_QUE>",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<SIMBOLO_ASIGNACION>",
    "<SIMBOLO_PUNTO_Y_COMA>",
    "<SIMBOLO_COMA>",
    "<SIMBOLO_PUNTO>",
    "<SIMBOLO_COMILLA_SIMPLE>",
    "\"\\\"\"",
    "<SIMBOLO_PARENTESIS_ABIERTO>",
    "<SIMBOLO_PARENTESIS_CERRADO>",
    "<SIMBOLO_CORCHETE_ABIERTO>",
    "<SIMBOLO_CORCHETE_CERRADO>",
    "<SIMBOLO_LLAVE_ABIERTA>",
    "<SIMBOLO_LLAVE_CERRADA>",
    "<NUMERO_ENTERO>",
    "<NUMERO_REAL>",
    "<CARACTER>",
    "<SIMBOLO_GUION_BAJO>",
    "<IDENTIFICADOR>",
    "<LETRA>",
    "<DIGITO>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMENTARIO_LINEAL>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 46>",
    "<ERROR_CARACTER>",
    "<ERROR_NUMERO_REAL>",
    "<ERROR_IDENTIFICADOR>",
    "<ERROR_SIMBOLO_INVALIDO>",
  };

}
