/* Generated By:JavaCC: Do not edit this line. cminusparserConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface cminusparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONDICIONAL_IF = 1;
  /** RegularExpression Id. */
  int CONDICIONAL_ELSE = 2;
  /** RegularExpression Id. */
  int DATO_INT = 3;
  /** RegularExpression Id. */
  int DATO_FLOAT = 4;
  /** RegularExpression Id. */
  int DATO_CHAR = 5;
  /** RegularExpression Id. */
  int RETORNAR_RETURN = 6;
  /** RegularExpression Id. */
  int VACIO_VOID = 7;
  /** RegularExpression Id. */
  int CICLO_WHILE = 8;
  /** RegularExpression Id. */
  int SIMBOLO_MAS = 9;
  /** RegularExpression Id. */
  int SIMBOLO_MENOS = 10;
  /** RegularExpression Id. */
  int SIMBOLO_POR = 11;
  /** RegularExpression Id. */
  int SIMBOLO_DIVISION = 12;
  /** RegularExpression Id. */
  int SIMBOLO_MODULO = 13;
  /** RegularExpression Id. */
  int SIMBOLO_MENOR_QUE = 14;
  /** RegularExpression Id. */
  int SIMBOLO_MENOR_IGUAL = 15;
  /** RegularExpression Id. */
  int SIMBOLO_MAYOR_QUE = 16;
  /** RegularExpression Id. */
  int SIMBOLO_MAYOR_IGUAL = 17;
  /** RegularExpression Id. */
  int SIMBOLO_COMPARACION = 18;
  /** RegularExpression Id. */
  int SIMBOLO_DIFERENTE = 19;
  /** RegularExpression Id. */
  int SIMBOLO_ASIGNACION = 20;
  /** RegularExpression Id. */
  int SIMBOLO_PUNTO_Y_COMA = 21;
  /** RegularExpression Id. */
  int SIMBOLO_COMA = 22;
  /** RegularExpression Id. */
  int SIMBOLO_PARENTESIS_ABIERTO = 23;
  /** RegularExpression Id. */
  int SIMBOLO_PARENTESIS_CERRADO = 24;
  /** RegularExpression Id. */
  int SIMBOLO_CORCHETE_ABIERTO = 25;
  /** RegularExpression Id. */
  int SIMBOLO_CORCHETE_CERRADO = 26;
  /** RegularExpression Id. */
  int SIMBOLO_LLAVE_ABIERTA = 27;
  /** RegularExpression Id. */
  int SIMBOLO_LLAVE_CERRADA = 28;
  /** RegularExpression Id. */
  int SIMBOLO_COMENTARIO_ABIERTO = 29;
  /** RegularExpression Id. */
  int SIMBOLO_COMENTARIO_CERRADO = 30;
  /** RegularExpression Id. */
  int NUEVA_LINEA = 31;
  /** RegularExpression Id. */
  int RETORNO_DE_CARRO = 32;
  /** RegularExpression Id. */
  int TABULACION = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"return\"",
    "\"void\"",
    "\"while\"",
    "<SIMBOLO_MAS>",
    "<SIMBOLO_MENOS>",
    "<SIMBOLO_POR>",
    "<SIMBOLO_DIVISION>",
    "<SIMBOLO_MODULO>",
    "<SIMBOLO_MENOR_QUE>",
    "\"<=\"",
    "<SIMBOLO_MAYOR_QUE>",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "<SIMBOLO_ASIGNACION>",
    "<SIMBOLO_PUNTO_Y_COMA>",
    "<SIMBOLO_COMA>",
    "<SIMBOLO_PARENTESIS_ABIERTO>",
    "<SIMBOLO_PARENTESIS_CERRADO>",
    "<SIMBOLO_CORCHETE_ABIERTO>",
    "<SIMBOLO_CORCHETE_CERRADO>",
    "<SIMBOLO_LLAVE_ABIERTA>",
    "<SIMBOLO_LLAVE_CERRADA>",
    "\"/*\"",
    "\"*/\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
  };

}
